obj-m += sys_cryptocopy.o

INC=/lib/modules/$(shell uname -r)/build/arch/x86/include

all: test_cryptocopy cryptocopy

test_cryptocopy: xhw1.c
	gcc -Wall -Werror -I$(INC)/generated/uapi -I$(INC)/uapi xhw1.c -o test_cryptocopy -lcrypto

cryptocopy:
	make -Wall -Werror -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
	rm -f test_cryptocopy
